### ISSUE TITLE
March 3rd update is the only version that works with Classic Era.

### ISSUE THREAD

**Issue by astothialo** [p3lim-wow/Molinari#100]
As the title says.

every time i've updated molinari it stops working so i've had to manually download the March 3rd update just to use it.

**Comment by p3lim** [comment]
You have to be more specific, as from my own tests Molinari works on Classic Era.

Which item does it not work with? Do you use any other addons (full list if possible)?

**Comment by astothialo** [comment]
i've been trying to disenchant various greens and when holding ALT it just doesnt do anything.
Here's a list of the addons i use:
Ace
Atlas
auctionator
badboy
badboy cleaner
bagnon
bigdebuffs
blu
cleaner classic
conroc
clique
DBM
dominos
elkbars
gathermate
handynotes
leatrix plus
leatrix maps
mobinfo
omnicc
parrot
pawn
pedler
postal
prat
questie
recount
rested xp
sexy map
silver dragon
spy
talented
tidy tip
weak auras
what training
xloot

As ive mentioned the march 3rd version works no problems. It's very weird.

**Comment by p3lim** [comment]
Which items specifically? I need to know so I can try to replicate it.
Also, how much enchanting skill do you have?

**Comment by p3lim** [comment]
Since there hasn't been a response for several weeks I'm going to assume it's already been fixed, or atleast should be with version 100100.107-Release.
