### ISSUE TITLE
Unable to prospect ore in Wrath Classic

### ISSUE THREAD

**Issue by chon379** [p3lim-wow/Molinari#106]
I have disabled bag addons and still can no longer prospect ore, I get no glow on the ore icon like before to click to prospect.

**Comment by p3lim** [comment]
Which ore? What is your jewelcrafting skill level?

**Comment by chon379** [comment]
450, titanium ore

**Comment by chon379** [comment]
Looks like it works with cobalt ore just fine! Just not titanium ore

**Comment by p3lim** [comment]
Yeah it's not in Molinari's list of ores, I'll sort that out.

**Comment by chon379** [comment]
Sweet thanks @p3lim !!!

**Comment by p3lim** [comment]
It was even noted down as missing by me, must've forgot it :P
https://github.com/p3lim-wow/Molinari/blob/a690e5f584dcd079bdb142fc6092854503781762/scripts/prospectable_classic.py#L7
