### ISSUE TITLE
Please update to latest .toc

### ISSUE THREAD

**Issue by ramseykj** [p3lim-wow/Molinari#12]
What version are you using? (don't say "latest" or "newest").
60000.35 (hope i got the correct number of zeros)

Can you reproduce it, and if you can, how?

If there was an error message, include it.
I keep getting the eror in my chat frame approximately every two or three minutes.  
"There are too many errors in your IU. As a result, your game experience may be degraded.  Diable or update the failing addons if you don't want to see this message again."

If it is a graphical issue, include a screenshot (use imgur or something)

**Comment by p3lim** [comment]
And you keep getting those errors with Molinari disabled?  
That error is not related to Interface versions, rather errors in addons.

If you're not seeing any error windows popping up you need to turn them on by going to the Escape menu, click the Interface button, select the Help section on the left and enable Error Messages or something along those lines

**Comment by ramseykj** [comment]
No I do not get the error when disabled

Karen

**Comment by p3lim** [comment]
I can't do much without a bug report, enable it and provide some details.
