### ISSUE TITLE
Support mass milling

### ISSUE THREAD

**Issue by Phanx** [p3lim-wow/Molinari#13]
6.2 added new "Mass Mill" spells for Draenor herbs that mill 20 herbs at a time instead of only 5. It would be nice if Molinari supported these to avoid clicking 4x as much as is really needed.

http://www.wowhead.com/search?q=mass+mill#professions

**Comment by p3lim** [comment]
The problem with this is that I cannot select manually which item in the bags should be processed, the profession window just picks one (probably the top-left-most in the bags), and the implementation is not really feasible.

I would rather say that for the items that can be processed in such a way (basically anything from Draenor), Molinari should not be used at all, as it's simply ineffective in comparison.

**Comment by Phanx** [comment]
Well, I wouldn't really mind if alt-clicking on, say, some Fireweed just emulated "open tradeskill frame, click Mass Mill Fireweed, click create all". If I only want to mill a specific stack of herbs (eg. I need to keep 12 for a recipe) I'm probably not going to use mass milling anyway.

**Comment by p3lim** [comment]
With the new professions API I might have to take a second look at this.

**Comment by p3lim** [comment]
Items cannot be mass-anything without the profession UI being open, which _can be opened_ (maybe additional modifier to trigger it), but it's unfeasible for two reasons:

1. When mass-milling, it's selecting _any_ item in the player's inventory, not the one under the cursor
2. Making sure that the player has the required recipe learned requires scanning the profession (which I've found very unfeasible to do, see https://github.com/p3lim-wow/LibProcessable/issues/14)

Unless someone finds a genious solution and sends me a PR, I'm going to close this issue.
