### ISSUE TITLE
cata update please

### ISSUE THREAD

**Issue by amey1956** [p3lim-wow/Molinari#143]
get the following lua error on login cata classic, same error on wrath/retail versions since there is no cata option.

**Describe the bug**
`3x Molinari/hack.lua:77: attempt to index global 'C_TradeSkillUI' (a nil value)
[string "@Molinari/hack.lua"]:77: in function `HasProfessionData'
[string "@Molinari/hack.lua"]:39: in function <Molinari/hack.lua:31>

Locals:
self = ForceLoadTradeSkillData {
 0 = <userdata>
 version = 3
 HasProfessionData = <function> defined @Molinari/hack.lua:76
 OnKeyDown = <function> defined @Molinari/hack.lua:54
 GetAnyProfessionID = <function> defined @Molinari/hack.lua:64
}
professionID = 773
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'C_TradeSkillUI' (a nil value)"
`

**How to reproduce**
milling does not work in wrath edition, tried retail to see if it helped at all, unable to mill using either version. 
**What did you expect?**
well, obviously i expected to mill a few hundred herbs

**Screenshots**

**Comment by p3lim** [comment]
Won't have time to do this until next week, but temporarily just rename "Molinari_Wrath.toc" to "Molinari_Cata.toc".

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/Molinari/commit/7122597cb92ad810ac8004aa8e723fa51e0da3c2
