### ISSUE TITLE
Translation: zhTW

### ISSUE THREAD

**Issue by seakoria** [p3lim-wow/Molinari#148]
### Which locale are these translations for?

zhTW (Chinese, Traditional, Taiwan)

### "Modifier to activate %s"

啟用%s的設置選項

### "Item Blocklist"

物品屏蔽列表

### "Block Item"

屏蔽物品

### "Items in this list will not be processed."

列表中的物品不會被處理

### "Block a new item by ID"

通過物品ID屏蔽一個新的物品

**Comment by p3lim** [comment]
Thanks!
