### ISSUE TITLE
Translation: zhCN

### ISSUE THREAD

**Issue by seakoria** [p3lim-wow/Molinari#149]
### Which locale are these translations for?

zhCN (Chinese, Simplified, PRC)

### "Modifier to activate %s"

启用%s的设置选项

### "Item Blocklist"

物品屏蔽列表

### "Block Item"

屏蔽物品

### "Items in this list will not be processed."

列表中的物品不会被处理

### "Block a new item by ID"

通过物品ID屏蔽一个新的物品

**Comment by p3lim** [comment]
Thanks!

**Comment by yleafcc** [comment]
![image](https://github.com/user-attachments/assets/ca18aefb-4ac9-4418-b61f-0fbbc963edb2)
## Interface: 110002, 110005
## Author: p3lim
## Version: 110000.121-Release
## Title: Molinari
## Notes: One-click Milling, Prospecting, Disenchanting, Lockpicking, and more!
## IconTexture: Interface\Icons\ability_miling
## SavedVariables: MolinariBlacklistDB, MolinariDB, MolinariDB2, MolinariDB3


I am using the latest version of the plugin, but the settings are not in Chinese

**Comment by p3lim** [comment]
@yleafcc Thanks for reporting, fixed in https://github.com/p3lim-wow/Molinari/commit/24f9e3b1448696a82248c3f484be89be657a8284
