### ISSUE TITLE
alt key doesn't

### ISSUE THREAD

**Issue by Sombreheros** [p3lim-wow/Molinari#15]
Molinari addon correctly installed and works. No LUA error.

Simply, alt key doesn't work anymore

**Comment by p3lim** [comment]
Please give me a full list of your addons.

**Comment by Sombreheros** [comment]
You can close this issue, unload all my addon and reload all of them, and works fine, don't know what's happened and how.

sorry.

**Comment by p3lim** [comment]
Would still like a list of all your addons, in case someone comes around with a similar issue and I can find a possible culprit.

**Comment by Sombreheros** [comment]
altotholic
auctionator
autoturnin
badboy
can I mog it
elephant
gather mate2
handynotes
legion wardrobe
master plan
msbt
molinari
paste
postal
quick talent
quickmark
server hop
skada
the undermine journal
tomtom
elvui
dbm

**Comment by p3lim** [comment]
Thanks
