### ISSUE TITLE
ADDON_ACTION_BLOCKED

### ISSUE THREAD

**Issue by flyingdutch87** [p3lim-wow/Molinari#165]
**Describe the bug**
Buggrabber Output:

1x [ADDON_ACTION_BLOCKED] AddOn 'Molinari' tried to call the protected function 'UNKNOWN()'.
[string "@!BugGrabber/BugGrabber.lua"]:485: in function <!BugGrabber/BugGrabber.lua:485>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCVar'
[string "@Blizzard_SharedXMLBase/CvarUtil.lua"]:11: in function <Blizzard_SharedXMLBase/CvarUtil.lua:9>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCVar'
[string "@Blizzard_SharedXMLBase/CvarUtil.lua"]:72: in function `SetValue'
[string "@Blizzard_Settings_Shared/Blizzard_Setting.lua"]:183: in function `SetValueInternal'
[string "@Blizzard_Settings_Shared/Blizzard_Setting.lua"]:67: in function `SetValue'
[string "@Blizzard_Settings_Shared/Blizzard_SettingControls.lua"]:398: in function <...lizzard_Settings_Shared/Blizzard_SettingControls.lua:394>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:144: in function <...eBlizzard_SharedXMLBase/CallbackRegistry.lua:143>
[string "=[C]"]: ?
[string "@Blizzard_SharedXMLBase/CallbackRegistry.lua"]:147: in function `TriggerEvent'
[string "@Blizzard_Settings_Shared/Blizzard_SettingControls.lua"]:347: in function <...lizzard_Settings_Shared/Blizzard_SettingControls.lua:346>

Locals:
_ = Frame {
}
event = "ADDON_ACTION_BLOCKED"
events = <table> {
}

**Comment by p3lim** [comment]
Not much I can do about this apart from writing a whole new settings panel replacing Blizzard's, Blizzard just needs to fix their stuff.

**Comment by p3lim** [comment]
Closing this as the settings got some big changes in 11.0.2, create a new issue if it persists after that version.
