### ISSUE TITLE
Settings not saving

### ISSUE THREAD

**Issue by Wraithlord2015** [p3lim-wow/Molinari#166]
**Describe the bug**

Using the most recent version of Molinari (110000.117-Release). No matter what modifier is chosen to activate Molinari, it does not save. Tried manually forcing a save by logging in a non safe zone/inn/rest area. Tried a manual download/fresh install after deleting all folders/related files. No error is thrown, the options are just simply not saved; so every time you log into the game - you need to reset the modifier in the addon options.

**How to reproduce**

Choose your modifier to activate Molinari. Log out. Log back in. The modifier selection you chose is not saved.

**What did you expect?**

Before TWW prepatch, Molinari would "remember" what modifier you selected to activate it.

**Screenshots**

Can provide screenshots if needed, but I think the description of the problem is pretty clear.

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/Dashi/commit/5e046071edbe745ee4b67699e125684e1371b7ef
