### ISSUE TITLE
Alt key won't trigger disenchant for TWW items.

### ISSUE THREAD

**Issue by tpoismans** [p3lim-wow/Molinari#169]
**Describe the bug**
When disenchanting green and blue items, holding the alt-key won't trigger the disenchant option. No glowing border on the item either.

**How to reproduce**
Hold Alt, hover over item

**What did you expect?**
Glowing item border + ability to disenchant

**Screenshots**
When holding alt:
![image](https://github.com/user-attachments/assets/cf8a968a-f016-4790-9f02-cd040370343c)

Normal disenchant (click+hover):
![image](https://github.com/user-attachments/assets/4b7e7f04-f90c-423d-8fbb-39af9f6f0074)

**Comment by p3lim** [comment]
Try without the bag addon, and tell me which one you use.

**Comment by tpoismans** [comment]
> Try without the bag addon, and tell me which one you use.

No bag addon. It's the combined bag from WoW
![image](https://github.com/user-attachments/assets/8dbdb49f-4201-4031-80ab-4302c79ee57a)

**Comment by p3lim** [comment]
I'm unable to reproduce this at all, even with the exact same item you showed in the screenshots. Check your settings (`/molinari`) and maybe try with _just_ Molinari enabled (and preferably bugsack+buggrabber to check for errors) to ensure there's no collision with other addons.

**Comment by tpoismans** [comment]
Disabled some addons, mainly altoholic and dependecies, emote splitter, instance achievement tracker, some raider.io ones and seems to be working again.
