### ISSUE TITLE
Cannot find a library instance of "Wasabi"

### ISSUE THREAD

**Issue by Roktaal** [p3lim-wow/Molinari#17]
Date: 2016-08-25 14:54:42
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Molinari\Config.lua line 9:
   Cannot find a library instance of "Wasabi".
Debug:
   [C]: error()
   !Swatter\Support\LibStub.lua:23: LibStub()
   Molinari\Config.lua:9: in main chunk
Locals:
(*temporary) = "Cannot find a library instance of "Wasabi"."

AddOns:
  Swatter, v5.21.5490 (SanctimoniousSwamprat)
  AchieveIt, v
  ACP, v3.4.28 
  AddOnSkins, v3.36
  Altoholic, vr171
  Auctionator, v4.0.10
  DataStore, vr59
  DataStoreAchievements, vr42
  DataStoreAgenda, vr23
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr36
  DataStoreContainers, vr53
  DataStoreCrafts, vr73
  DataStoreCurrencies, vr31
  DataStoreGarrisons, vr16
  DataStoreInventory, vr46
  DataStoreMails, vr46
  DataStorePets, vr39
  DataStoreQuests, vr36
  DataStoreReputations, vr37
  DataStoreSpells, vr27
  DataStoreStats, vr26
  DataStoreTalents, vr54
  DBMCore, v
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  ElvUI, v10.14
  ElvUISLE, v3.12
  FollowerLocationInfo, v0.12-release2
  FollowerLocationInfoData, v0.9-release
  HandyNotes, vv1.4.8
  HandyNotesDraenorTreasures, v1.20
  InFlightLoad, v6.2.001
  MacroToolkit, vv7.0.1.1
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.146
  MogIt, v3.6.3
  MogItCloth, v3.6.3
  MogItCosmetic, v3.6.3
  MogItLeather, v3.6.3
  MogItMail, v3.6.3
  MogItOneHanded, v3.6.3
  MogItOther, v3.6.3
  MogItPlate, v3.6.3
  MogItRanged, v3.6.3
  MogItTwoHanded, v3.6.3
  Molinari, v70000.37-Release
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=4ac)

**Comment by Roktaal** [comment]
followed by...

Date: 2016-08-25 14:54:42
ID: 2
Error occured in: Global
Count: 1
Message: ..\AddOns\Molinari\Molinari.lua line 89:
   Cannot find a library instance of "LibProcessable".
Debug:
   [C]: error()
   !Swatter\Support\LibStub.lua:23: LibStub()
   Molinari\Molinari.lua:89: in main chunk
Locals:
(*temporary) = "Cannot find a library instance of "LibProcessable"."

AddOns:
  Swatter, v5.21.5490 (SanctimoniousSwamprat)
  AchieveIt, v
  ACP, v3.4.28 
  AddOnSkins, v3.36
  Altoholic, vr171
  Auctionator, v4.0.10
  DataStore, vr59
  DataStoreAchievements, vr42
  DataStoreAgenda, vr23
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr36
  DataStoreContainers, vr53
  DataStoreCrafts, vr73
  DataStoreCurrencies, vr31
  DataStoreGarrisons, vr16
  DataStoreInventory, vr46
  DataStoreMails, vr46
  DataStorePets, vr39
  DataStoreQuests, vr36
  DataStoreReputations, vr37
  DataStoreSpells, vr27
  DataStoreStats, vr26
  DataStoreTalents, vr54
  DBMCore, v
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  ElvUI, v10.14
  ElvUISLE, v3.12
  FollowerLocationInfo, v0.12-release2
  FollowerLocationInfoData, v0.9-release
  HandyNotes, vv1.4.8
  HandyNotesDraenorTreasures, v1.20
  InFlightLoad, v6.2.001
  MacroToolkit, vv7.0.1.1
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.146
  MogIt, v3.6.3
  MogItCloth, v3.6.3
  MogItCosmetic, v3.6.3
  MogItLeather, v3.6.3
  MogItMail, v3.6.3
  MogItOneHanded, v3.6.3
  MogItOther, v3.6.3
  MogItPlate, v3.6.3
  MogItRanged, v3.6.3
  MogItTwoHanded, v3.6.3
  Molinari, v70000.37-Release
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=4ac)

**Comment by p3lim** [comment]
It's an issue with the libraries, I'll fix that.

**Comment by p3lim** [comment]
Fixed with https://github.com/p3lim-wow/Wasabi/commit/ad1af2b638a7d20ead41273c3e1ff37646beac58 and https://github.com/p3lim-wow/LibProcessable/commit/0fe146b4cb8699d6a34ac7ad5401b7e7369a1dc6, new version pushed.

**Comment by Roktaal** [comment]
Thank you very much for a fast response but unfortunately with 70000.38-Release a new issue popped up tied to the libraries...

Date: 2016-08-25 15:44:43
ID: -1
Error occured in: Global
Count: 1
Message: ...dOns\Molinari\libs\LibProcessable\LibProcessable.lua line 446:
   attempt to call global 'GetAuctionItemClasses' (a nil value)
Debug:
   ...dOns\Molinari\libs\LibProcessable\LibProcessable.lua:446:
      ...dOns\Molinari\libs\LibProcessable\LibProcessable.lua:404
Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "PLAYER_LOGIN"
(*temporary) = nil
(*temporary) = "attempt to call global 'GetAuctionItemClasses' (a nil value)"
inscriptionSkill = 0
jewelcraftingSkill = 0
enchantingSkill = 700
blacksmithingSkill = 0
lib = <table> {
 IsProspectable = <function> defined @Interface\AddOns\Molinari\libs\LibProcessable\LibProcessable.lua:42
 containers = <table> {
 }
 enchantingBuildings = <table> {
 }
 IsMillable = <function> defined @Interface\AddOns\Molinari\libs\LibProcessable\LibProcessable.lua:22
 ores = <table> {
 }
 IsOpenable = <function> defined @Interface\AddOns\Molinari\libs\LibProcessable\LibProcessable.lua:380
 IsDisenchantable = <function> defined @Interface\AddOns\Molinari\libs\LibProcessable\LibProcessable.lua:323
 herbs = <table> {
 }
}
hasEnchantingBuilding = nil
itemClasses = <table> {
}

AddOns:
  Swatter, v5.21.5490 (SanctimoniousSwamprat)
  AchieveIt, v
  ACP, v3.4.28 
  AddOnSkins, v3.36
  Altoholic, vr171
  Auctionator, v4.0.10
  DataStore, vr59
  DataStoreAchievements, vr42
  DataStoreAgenda, vr23
  DataStoreAuctions, v6.0.001
  DataStoreCharacters, vr36
  DataStoreContainers, vr53
  DataStoreCrafts, vr73
  DataStoreCurrencies, vr31
  DataStoreGarrisons, vr16
  DataStoreInventory, vr46
  DataStoreMails, vr46
  DataStorePets, vr39
  DataStoreQuests, vr36
  DataStoreReputations, vr37
  DataStoreSpells, vr27
  DataStoreStats, vr26
  DataStoreTalents, vr54
  DBMCore, v
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  ElvUI, v10.14
  ElvUISLE, v3.12
  FollowerLocationInfo, v0.12-release2
  FollowerLocationInfoData, v0.9-release
  FollowerLocationInfoJournal, v0.12-release2
  HandyNotes, vv1.4.8
  HandyNotesDraenorTreasures, v1.20
  InFlightLoad, v6.2.001
  MacroToolkit, vv7.0.1.1
  MacroToolkitIcons, v7.0.0.0
  MasterPlanA, vA
  MikScrollingBattleText, v5.7.146
  MogIt, v3.6.3
  MogItCloth, v3.6.3
  MogItCosmetic, v3.6.3
  MogItLeather, v3.6.3
  MogItMail, v3.6.3
  MogItOneHanded, v3.6.3
  MogItOther, v3.6.3
  MogItPlate, v3.6.3
  MogItRanged, v3.6.3
  MogItSetTransmog, v1.4.0
  MogItTwoHanded, v3.6.3
  Molinari, v70000.38-Release
  MountFarmHelper, v2.0
  Postal, vv3.5.8
  Quester, v7.0.3.3
  RaidAchieveFilter, v1.9
  SimpleRareElite, v1.27
  Skada, v1.5-7
  Stubby, v5.21.5490 (SanctimoniousSwamprat)
  ThogarAssist, v
  ZoneLevelInfo, v2.1.4
  BlizRuntimeLib_enUS v7.0.3.70000 <none>
  (ck=60f)
