### ISSUE TITLE
LibProcessable-12.lua:446 error

### ISSUE THREAD

**Issue by class2u** [p3lim-wow/Molinari#18]
Hi p3lim, thank you for making this great addon. It is very convenient and useful. I get an error when loading it. But the function is working.

- What version are you using?

70000.38-Release

- Can the issue be reproduced, and if so, how?

Load this addon and login to game.

- If there was an error message, please include it.

`` 1x ...dOns\Molinari\libs\LibProcessable\LibProcessable-12.lua:446: attempt to call global 'GetAuctionItemClasses' (a nil value)
...dOns\Molinari\libs\LibProcessable\LibProcessable-12.lua:446: in function <...dOns\Molinari\libs\LibProcessable\LibProcessable.lua:404>

Locals:
self = <unnamed> {
 0 = <userdata>
}
event = "PLAYER_LOGIN"
(*temporary) = nil
(*temporary) = "attempt to call global 'GetAuctionItemClasses' (a nil value)"
inscriptionSkill = 0
jewelcraftingSkill = 0
enchantingSkill = 0
blacksmithingSkill = 0
lib = <table> {
 IsProspectable = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:42
 containers = <table> {
 }
 enchantingBuildings = <table> {
 }
 IsMillable = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:22
 ores = <table> {
 }
 IsOpenable = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:380
 IsDisenchantable = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:323
 herbs = <table> {
 }
}
hasEnchantingBuilding = nil
itemClasses = <table> {
}

**Comment by p3lim** [comment]
Fixed with https://github.com/p3lim-wow/LibProcessable/commit/ff6e8b84757905ccf5e9f81867a20cc3d4e5b581
