### ISSUE TITLE
New feature - Enchanting: Gleaming Shatter

### ISSUE THREAD

**Issue by Marquize-sys** [p3lim-wow/Molinari#186]
With the fairly recent addition for enchanters to shatter gleaming shards into storm dust it would be a fine candidate to implement into your addon. 
While I'm no programmer and not sure how this works functionally for the addon, it seems to me that it should be an similar implementation to already existing functions, such as crushing gems and pilfer parts.

**Comment by p3lim** [comment]
Fixed in https://github.com/p3lim-wow/Molinari/pull/189
