### ISSUE TITLE
Feature Request: use other key

### ISSUE THREAD

**Issue by class2u** [p3lim-wow/Molinari#19]
Hi p3lim, Thank you for making this great addon. Could you please add an option to choose key other than Alt? Because my bag addon already uses Alt+clicking for customize categories. It will be very very helpful If I can use key like Ctrl+Alt+clicking or Alt+right clicking to process the items.

**Comment by p3lim** [comment]
I've been denying this feature request for quite some time because of all the modifiers used by the game already.
However, adding an _additional_ modifier should be feasible, I'll take a look into it.

**Comment by class2u** [comment]
Thank you  :+1:
