### ISSUE TITLE
Leystone Lockbox

### ISSUE THREAD

**Issue by p-90** [p3lim-wow/Molinari#21]
**- What version are you using?**
70100.43-Release.

**- Can the issue be reproduced, and if so, how?**
Holding Alt and clicking the Leystone Lockbox doesn't unlock it like the other lockboxes do.

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/LibProcessable/commit/c2d71d63dd64d23499abf416f1cad6b6757947b3

New version will be out this weekend, hopefully™.
