### ISSUE TITLE
Legion enchantment quest items

### ISSUE THREAD

**Issue by periflo90** [p3lim-wow/Molinari#24]
**- What version are you using?**
70300.52-Release.

There are three Legion enchantment quest items which need to be disenchanted and I thought Molinari could support them for convenience reasons. Here they are:

http://www.wowhead.com/item=137195/highmountain-armor
http://www.wowhead.com/item=137221/enchanted-raven-sigil
http://www.wowhead.com/item=137286/fel-crusted-rune

**Comment by p3lim** [comment]
Those are already supported.
https://github.com/p3lim-wow/LibProcessable/commit/ae23e1d103c1028b25ab6902cfcfc2a35f255df6
https://github.com/p3lim-wow/LibProcessable/blob/master/LibProcessable.lua#L74

**Comment by periflo90** [comment]
I tried it recently (I don't recall when, but it was way after that issue was closed) and I couldn't. I have completed those quests since then but I could do them again on another character. Please leave this open so I can update my findings.

**Comment by periflo90** [comment]
Just tried on my alt and I can't disenchant those quest items using Molinari (I Hold the Alt key and it doesn't react to those items when hovered, nor I can't disenchant them like that).

**Comment by p3lim** [comment]
> nor I can't disenchant them like that

You mean disenchant them by clicking the spell then clicking the item?

**Comment by periflo90** [comment]
I mean holding the Alt key and clicking on the item like normal pieces of gear.

**Comment by p3lim** [comment]
Fixed in r24 of LibProcessable, I'll push Molinari with the updated library once I'm done testing other things.

**Comment by periflo90** [comment]
Thank you!
