### ISSUE TITLE
Issues using in BfA Beta

### ISSUE THREAD

**Issue by Elekayl** [p3lim-wow/Molinari#25]
I have been using what I believe to be the most recent version, 70300.53-Release, which says it is compatible with version 8.0.1

Every time I log into a character with Molinari enabled, I get the following error:

Message: Error loading Interface\AddOns\Molinari\libs\Wasabi\LibStub\LibStub.lua
Time: Wed Jun 27 10:32:43 2018
Count: 4

Also, so far I have used this fine with enchanting, but it doesn't appear to be working with prospecting or milling the new BfA materials.  It still works fine with prior version materials.

If I can assist with any more info please feel free to contact me.

**Comment by p3lim** [comment]
> Every time I log into a character with Molinari enabled, I get the following error:

Thanks for letting me know.

> Also, so far I have used this fine with enchanting, but it doesn't appear to be working with prospecting or milling the new BfA materials. It still works fine with prior version materials.

The materials haven't been added yet.

**Comment by Elekayl** [comment]
Thank you for the prompt response!

> The materials haven't been added yet.
Feel free to supply me with a list of them to save me some work :).

HERBS: Riverbud,  Sea Stalk,  Star Moss,  Akunda's Bite,  Winter's Kiss,  Siren's Pollen,  Anchor Weed

ORE: Monelite Ore,  Platinum Ore,  Storm Silver Ore

**Comment by p3lim** [comment]
Thank you for that list. I won't promise any new releases until the prepatch though.
