### ISSUE TITLE
Unable to mill certain weeds

### ISSUE THREAD

**Issue by Rhilyn** [p3lim-wow/Molinari#26]
I was attempting to mill a bunch of the weeds I have stashed and came across quite a few that your mod isn't working with. I have tried with my normal mods on and once again with all of my mods but molinari turned off and they're still not working. It's not an issue with my inscription skill level because it's almost at max, the problem weeds are random from WoD expansion all the way back to classic weeds. 

Here are my list of weeds that will not mill with your mod. (They still can be milled the "normal" way) This may not be a full list, it's just what I had in my bank. If I come across any more I will add them. 

Kingsblood, Liferoot, Ghost Mushroom, Dreamfoil, Gromsblood, Sorrowmoss, Firebloom, Felweed, Netherbloom, Nightmare Vine, Dreaming Glory, Adders Tongue, Terocone, Talandra's Rose, Cinderbloom, Deadnettle, Icethorn, Fool's Cap, Rain Poppy, Snow Lily, Green Tea Leaf, Silkweed, Nagrand Arrowbloom

- What version are you using? I am using 80000.54-Release with WoW version 8.0.1.27144
- Can the issue be reproduced, and if so, how? Unknown, it happens every time. 
- If there was an error message, please include it. N/A
- If there is a graphical issue, please include a screenshot (you can drag-n-drop here). N/A

Update - This is also happening when trying to use prospecting on certain ores. I have a limited supply to test but so far it's not working on Black and White Trillium ore, Ghost Iron ore, Kyparite, Blackrock ore, True Iron ore.

**Comment by nancikennedy** [comment]
The answer is yes. I edited my local "Molinari\libs\LibProcessable.lua" file and changed the skill level of all the herb and ore entries to 1, as that is the level listed for the corresponding objects on wowhead. I can now mill/prospect everything again.

**Comment by p3lim** [comment]
They changed all the herbs to be millable at rank 1, but that does not apply to all ores sadly.
I'm working on an update to fix everything.

**Comment by Rhilyn** [comment]
Awesome, thank you so much.

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/Molinari/commit/ea5a935cd84e871e1c7ff31ab2b607bcabb90dd1
