### ISSUE TITLE
LibProcessable Error

### ISSUE THREAD

**Issue by Sythalin** [p3lim-wow/Molinari#27]
- What version are you using?

> 80000.55-Release

- If there was an error message, please include it.

> 1x ...dOns\Molinari\libs\LibProcessable\LibProcessable-27.lua:242: bad argument #1 to '(for generator)' (table expected, got nil)
> [C]: in function `(for generator)'
> ...dOns\Molinari\libs\LibProcessable\LibProcessable-27.lua:242: in function <...dOns\Molinari\libs\LibProcessable\LibProcessable.lua:237>
> ...dOns\Molinari\libs\LibProcessable\LibProcessable-27.lua:284: in function <...dOns\Molinari\libs\LibProcessable\LibProcessable.lua:280>
> 
> Locals:
> (*temporary) = nil
> (*temporary) = nil
> (*temporary) = "table expected, got nil"

**Comment by p3lim** [comment]
When did this happen? During login?
What professions do you have on that character?
