### ISSUE TITLE
Lua error 

### ISSUE THREAD

**Issue by Colmpriest** [p3lim-wow/Molinari#30]
I'm using the newest version of your addon, and keep getting a lua error. The addon seems to work properly, but wanted to make you aware.  The error:

1x [ADDON_ACTION_BLOCKED] AddOn 'Molinari' tried to call the protected function 'SecureStateDriverManager:SetAttribute()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: in function `SetAttribute'
FrameXML\SecureStateDriver.lua:10: in function <FrameXML\SecureStateDriver.lua:8>
(tail call): ?
Molinari\Molinari-80000.58-Release.lua:98: in function `UpdateModifier'
Molinari\Config.lua:27: in function `callback'
Molinari\libs\Wasabi\Wasabi-6.lua:327: in function `Fire'
Molinari\libs\Wasabi\Wasabi-6.lua:160: in function <Molinari\libs\Wasabi\Wasabi.lua:153>
[C]: in function `pcall'
FrameXML\InterfaceOptionsFrame.lua:209: in function <FrameXML\InterfaceOptionsFrame.lua:208>
[C]: in function `securecall'
FrameXML\InterfaceOptionsFrame.lua:232: in function <FrameXML\InterfaceOptionsFrame.lua:224>

Locals:
InCombatSkipped

Thanks, and great addon.

**Comment by p3lim** [comment]
When did this happen? During combat? If so, did you open your bags and that triggered it? If so, are you using any bag addon?

**Comment by Colmpriest** [comment]
It happens on log in. I'm not using any bag addon, but am using elvui. It's been happening for a few days, but didn't think to report it. My apologies.

**Comment by Colmpriest** [comment]
Just did another check.  It must be happening when I'm in combat. I just relogged to check, and it didn't bring up the error.

**Comment by p3lim** [comment]
Pretty sure this is an issue with ElvUI, feel free to let them know about this.
