### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SegoItCh** [p3lim-wow/Molinari#43]
```
Message: [ADDON_ACTION_BLOCKED] AddOn 'Molinari' tried to call the protected function 'SecureStateDriverManager:SetAttribute()'.
Time: Wed Aug 12 06:00:16 2020
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Molinari' tried to call the protected function 'SecureStateDriverManager:SetAttribute()'.
Interface\FrameXML\SecureStateDriver.lua:10: in function <Interface\FrameXML\SecureStateDriver.lua:8>
(tail call): ?
Interface\AddOns\Molinari\Molinari.lua:99: in function `UpdateModifier'
Interface\AddOns\Molinari\Config.lua:27: in function `callback'
Interface\AddOns\Molinari\libs\Wasabi\Wasabi.lua:329: in function `Fire'
Interface\AddOns\Molinari\libs\Wasabi\Wasabi.lua:162: in function <Interface\AddOns\Molinari\libs\Wasabi\Wasabi.lua:155>
[C]: in function `pcall'
Interface\FrameXML\InterfaceOptionsFrame.lua:209: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:208>
[C]: in function `securecall'
Interface\FrameXML\InterfaceOptionsFrame.lua:232: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:224>
[C]: in function `Click'
...\AddOns\RCLootCouncil_Classic\RCLootCouncil\core.lua:1113: in function <...\AddOns\RCLootCouncil_Classic\RCLootCouncil\core.lua:1112>
[C]: in function `Click'
Interface\FrameXML\UIParent.lua:3353: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals: <none>
```

**Comment by p3lim** [comment]
Did you happen to be in combat when you clicked "Okay" in the options? Only thing I can think of that could have caused this, and I can fix that.

**Comment by SegoItCh** [comment]
Maybe, fix it, and we will see

**Comment by SegoItCh** [comment]
I still getting error

**Comment by p3lim** [comment]
See https://github.com/p3lim-wow/Molinari/commit/b4975e15b5515c9c3bf358296603ec45b6913629

**Comment by SegoItCh** [comment]
Update on curse?

**Comment by SegoItCh** [comment]
Message: [ADDON_ACTION_BLOCKED] AddOn 'Molinari' tried to call the protected function 'SecureStateDriverManager:SetAttribute()'.
Time: Fri Oct  9 08:34:25 2020
Count: 1
Stack: [ADDON_ACTION_BLOCKED] AddOn 'Molinari' tried to call the protected function 'SecureStateDriverManager:SetAttribute()'.
(tail call): ?
Interface\AddOns\Molinari\Molinari.lua:99: in function `UpdateModifier'
Interface\AddOns\Molinari\Config.lua:27: in function `callback'
Interface\AddOns\Molinari\libs\Wasabi\Wasabi.lua:329: in function `Fire'
Interface\AddOns\Molinari\libs\Wasabi\Wasabi.lua:162: in function <Interface\AddOns\Molinari\libs\Wasabi\Wasabi.lua:155>
[C]: in function `pcall'
Interface\FrameXML\InterfaceOptionsFrame.lua:209: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:208>
[C]: in function `securecall'
Interface\FrameXML\InterfaceOptionsFrame.lua:232: in function <Interface\FrameXML\InterfaceOptionsFrame.lua:224>

Locals: <none>

**Comment by p3lim** [comment]
Please stop spamming, this issue is already resolved and a new version will be released for the prepatch.
