### ISSUE TITLE
Lockboxes not highlighting on rogue

### ISSUE THREAD

**Issue by tyrexis26** [p3lim-wow/Molinari#46]
**Describe the bug**
When I open my inventory and use alt over a lockbox, nothing happens.  I reloaded after turning off any other addon throwing up an error.

**How to reproduce**
Log in and hit the alt key while the mouse is over a lockbox in inventory

**What did you expect?**
For the lockbox to be highlighted

Error:

4x ...dOns\Molinari\libs\LibProcessable\LibProcessable-44.lua:94: attempt to compare number with nil
[string "@Molinari\libs\LibProcessable\LibProcessable-44.lua"]:94: in function `IsDisenchantable'
[string "@Molinari\Molinari-90000.69-Release.lua"]:150: in function <Molinari\Molinari.lua:130>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "@TradeSkillMaster\LibTSM\Service\ItemTooltipClasses\Wrapper.lua"]:98: in function `SetBagItem'
[string "@FrameXML\ContainerFrame.lua"]:1321: in function `ContainerFrameItemButton_OnUpdate'
[string "@FrameXML\ContainerFrame.lua"]:1368: in function `ContainerFrameItemButton_OnEnter'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:363: in function `ShowTooltip'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:334: in function `UpdateTooltip'
[string "@Bagnon\common\Wildpants\classes\item.lua"]:174: in function <...faceBagnon\common\Wildpants\classes\item.lua:173>

Locals:
self = <table> {
 professionCategories = <table> {
 }
 HasProfession = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:254
 containers = <table> {
 }
 herbs = <table> {
 }
 IsOpenableProfession = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:189
 enchantingItems = <table> {
 }
 IsProspectable = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:58
 IsDisenchantable = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:81
 ores = <table> {
 }
 IsOpenable = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:161
 GetProfessionCategories = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:267
 IsMillable = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:31
}
item = "|cffffffff|Hitem:169475::::::::50:260:::::::|h[]|h|r"
itemID = 169475
_ = nil
_ = nil
quality = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
_ = nil
class = nil
subClass = nil
(*temporary) = 2
(*temporary) = "attempt to compare number with nil"
LE_ITEM_QUALITY_UNCOMMON = 2
LE_ITEM_QUALITY_EPIC = 4
LE_ITEM_CLASS_ARMOR = 4
LE_ITEM_CLASS_WEAPON = 2
LE_ITEM_CLASS_GEM = 3
LE_ITEM_SUBCLASS_ARTIFACT = 11

**Comment by p3lim** [comment]
Will take a look at this later tonight if the authentication servers decide to play nicely.

**Comment by p3lim** [comment]
Should be fixed with https://github.com/p3lim-wow/LibProcessable/commit/536dd448ceba69b1ec5b2051efe5f7c8562816ad, let me know, a new version has been pushed.

**Comment by tyrexis26** [comment]
Working, thank you.
