### ISSUE TITLE
Thorium Lockboxes

### ISSUE THREAD

**Issue by Scrogador** [p3lim-wow/Molinari#47]
Unable to target and open Thorium Lockboxes as a rogue.  All other lockboxes work so far.

**Comment by p3lim** [comment]
Which game client? Which version of Molinari?

**Comment by Scrogador** [comment]
Game client?  You mean WoW?  Also I am using whatever the latest release
from Twitch is.  Since the 9.0 updates to Molinari I have noticed it has
not worked.  All other lockboxes work just fine, just not the Thorium
Lockbox in particular.

**Comment by p3lim** [comment]
> Game client?  You mean WoW?

I mean classic or retail.

**Comment by Scrogador** [comment]
Retail

**Comment by p3lim** [comment]
That item should no longer be available in the game, how did you get that?

**Comment by Scrogador** [comment]
In Retail?  I get it all the time from farming.  Lockbox drop rates and
names have not changed from what I can tell.  I multibox and I can pull all
lockbox now, just as before.  I got some 2 days ago.

**Comment by p3lim** [comment]
Watch out for a new version coming out soon.
