### ISSUE TITLE
Item Equip when loot window is open

### ISSUE THREAD

**Issue by KittenWizard** [p3lim-wow/Molinari#5]
It seems that alt-left clicking on an item when the loot window is open (which happens occasionally when disenchanting lots of items due to blizzards autoloot bug) causes the selected item to be swapped with the characters currently equipped item.

This is a MAJOR problem - I already lost an item before noticing my item was swapped.

**Comment by p3lim** [comment]
Fixed with 85fb4995c207f81adf9d665a0bd5ce7a25f9648d
