### ISSUE TITLE
utilizing alt does not activate the addon.  I have checked my keybindings in the addon and it is set to "alt"

### ISSUE THREAD

**Issue by Eereinith** [p3lim-wow/Molinari#50]
**Describe the bug**

**How to reproduce**

**What did you expect?**

**Screenshots**

**Comment by p3lim** [comment]
Which version of Molinari?
What item?
Which professions do you have, and at what skill?

**Comment by Eereinith** [comment]
My comments are in the body of your email.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Adrian L Lange <notifications@github.com> Date: 1/15/21  5:40 AM  (GMT-05:00) To: p3lim-wow/Molinari <Molinari@noreply.github.com> Cc: Eereinith <heavydist1@aol.com>, Author <author@noreply.github.com> Subject: Re: [p3lim-wow/Molinari] utilizing alt does not activate the addon.  I have checked my keybindings in the addon and it is set to "alt" (#50) 
Which version of Molinari? 9.0.2 release date 12.29.2020
What item? Anything I want to disenchant in my bag.
Which professions do you have, and at what skill? Enchanting and tailoring

**Comment by p3lim** [comment]
Are you using any bag addons?

**Comment by Eereinith** [comment]
Adi bags.  However I have had that addon for several expacs now with molinari.  Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Adrian L Lange <notifications@github.com> Date: 1/15/21  12:28 PM  (GMT-05:00) To: p3lim-wow/Molinari <Molinari@noreply.github.com> Cc: Eereinith <heavydist1@aol.com>, Author <author@noreply.github.com> Subject: Re: [p3lim-wow/Molinari] utilizing alt does not activate the addon.  I have checked my keybindings in the addon and it is set to "alt" (#50) 
Are you using any bag addons?

**Comment by p3lim** [comment]
I am unable to replicate this issue, under the same conditions using the latest version.
Have you tried with Molinari as the only addon enabled? If not, try that, then enable addons a couple at a time until it no longer works, you should be able to find out if there is another addon preventing it from working.

**Comment by Lofbergio** [comment]
Im having the same issue after updating to upstream, going from .73 release.

i am using a bag addon called T-Bag but worked fine in the previous versions.
