### ISSUE TITLE
Lua error [Classic ERA]

### ISSUE THREAD

**Issue by Altoholic** [p3lim-wow/Molinari#55]
**How to reproduce**
at every login

2x ...dOns\Molinari\libs\LibProcessable\LibProcessable-49.lua:316: table index is nil
...dOns\Molinari\libs\LibProcessable\LibProcessable-49.lua:316: in main chunk

Locals:
MAJOR = "LibProcessable"
MINOR = 49
lib = <table> {
 IsProspectable = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:59
 IsOpenableProfession = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:223
 IsMillable = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:31
 HasProfession = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:288
 IsOpenable = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:192
 GetProfessionCategories = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:301
 IsDisenchantable = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:84
}
oldMinor = nil
CLASSIC = true
LE_ITEM_QUALITY_UNCOMMON = 2
LE_ITEM_QUALITY_EPIC = 4
LE_ITEM_CLASS_ARMOR = 4
LE_ITEM_CLASS_WEAPON = 2
LE_ITEM_CLASS_GEM = 3
LE_ITEM_ARMOR_COSMETIC = 5
LE_ITEM_SUBCLASS_ARTIFACT = 11
LE_ITEM_EQUIPLOC_SHIRT = 4
professions = <table> {
}
GetBlacksmithingPick = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:107
GetJewelcraftingPick = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:156
GetInscriptionPick = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:164
GetEngineeringPick = <function> defined @Molinari\libs\LibProcessable\LibProcessable.lua:174
(*temporary) = <table> {
 Tailoring = 197
 Blacksmithing = 164
 Skinning = 393
 Alchemy = 171
 Mining = 186
 Engineering = 202
 Leatherworking = 165
 Herbalism = 182
 Enchanting = 333
}
(*temporary) = nil
(*temporary) = 25229
(*temporary) = "Tailoring"
(*temporary) = nil
(*temporary) = 136249
(*temporary) = 0
(*temporary) = 0
(*temporary) = 0
(*temporary) = 3908
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "table index is nil"

**Comment by p3lim** [comment]
Please try out this alpha version just to confirm the fix worked:
https://github.com/p3lim-wow/Molinari/suites/2800283615/artifacts/63122739

You'll need to enable loading out-of-date addons.

**Comment by Altoholic** [comment]
No more error, everything seem to work fine. TY!
