### ISSUE TITLE
Disenchanting Two-handed maces

### ISSUE THREAD

**Issue by Chanizu** [p3lim-wow/Molinari#58]
I noticed it was fixed for the retail version but the issue still exists in the TBC classic version.
Running this version
![image](https://user-images.githubusercontent.com/41269259/132899295-6d999306-37ae-4579-86e9-68a3e1ea39ce.png)

**Comment by p3lim** [comment]
It's fixed in the classic/BCC versions too, just the release got messed up. I'll poke the packager people and see if they can get their tooling fixed.

**Comment by p3lim** [comment]
Tooling has been fixed for some time.
