### ISSUE TITLE
Update for WOTLK Classic

### ISSUE THREAD

**Issue by danjohnso** [p3lim-wow/Molinari#67]
**Describe the bug**
This addon does not work for milling in WOTLK classic.

**How to reproduce**
Get stacks of herbs, press key combination and select herbs.  Herbs just flash all of a similar type, no action is taken.

**What did you expect?**
The stack of herbs to be milled

I verified disenchant is still working on a different toon, so it appears to be an issue with milling specifically, probably because this build is for TBC.  Prepatch also launches tomorrow so you should update the TOC if you have a chance.

**Comment by p3lim** [comment]
Someone would have to submit patches for the herbs, ores and lockboxes for this in https://github.com/p3lim-wow/LibProcessable, in a compatible manner, as I do not and have no intention to play classic.

**Comment by adnedelcu** [comment]
Created a patch to add the skill in the profession list for classic. I have tested only on a small version of the plants since my skill is not high enough.

**Comment by p3lim** [comment]
Thanks @adnedelcu!

**Comment by p3lim** [comment]
I assume from that PR that milling works fine in Molinari, although herb compatibility testing was limited?

**Comment by adnedelcu** [comment]
Yes, exactly. I only tested up to Mageroyal. I have seen that there is a piece of code for checking if the player has the profession high enough for it, but for all plants is set to 1.
That could be improved in the future. (I can try to do it tonight, but I need to find where I can get that information from)

**Comment by p3lim** [comment]
In retail all herbs and most ores can be milled/prospected with 1 skill in the profession.
I'll go through the history and pull the old numbers out and use them.

I'd also have to re-implement the skill logic, which I've failed to do before (see https://github.com/p3lim-wow/LibProcessable/issues/14).

**Comment by p3lim** [comment]
@adnedelcu I know it's a bit early, but any chance you could check in-game if [Fire Seed](https://www.wowhead.com/wotlk/item=39969/fire-seed) is millable? The item existed until 3.0.8 when WotLK was current, but wowhead lists the item as available in the game at classic's 3.4 patch level.

If it exists and is millable, I'd very much like to know what skill level is required to mill it.

**Comment by adnedelcu** [comment]
Haven't gotten to it yet, but will keep an eye out for it.

**Comment by p3lim** [comment]
Added full support for the new herbs, ores, lockboxes etc in LibProcessable, please try it out and see if you have any issues and that the skill level check works correctly.

A packaged version can be found under the "Artifacts" header here:  
https://github.com/p3lim-wow/LibProcessable/actions/runs/3002992432

**Comment by keyboardturner** [comment]
atm the issue I get is this lua error with [GetProfessions()](https://wowpedia.fandom.com/wiki/API_GetProfessions).

5x ...dOns\Molinari\libs\LibProcessable\LibProcessable-55.lua:383: attempt to call global 'GetProfessions' (a nil value)
[string "@Molinari\libs\LibProcessable\LibProcessable-55.lua"]:383: in function <...dOns\Molinari\libs\LibProcessable\LibProcessable.lua:380>

**Comment by p3lim** [comment]
@keyboardturner which game version?

**Comment by keyboardturner** [comment]
sorry wrath classic, if the above version was not intended for wrath then my mistake

**Comment by p3lim** [comment]
I'm just making sure, as there are 4 current game versions available :P

**Comment by adnedelcu** [comment]
Only 3 that are live. 4 if you consider beta for Dragonflight.

1. Classic
2. Wrath Classic
3. Shadowlands
4. Dragonflight

**Comment by p3lim** [comment]
That should do it, feel free to test and report back.

**Comment by Macumbatbc** [comment]
Hello, i just tested it, i added : https://github.com/p3lim-wow/LibProcessable/commit/0755edaeba5ca5553dbe97cadb6029342691caea

And no errors, and it works ! ty ! :)

**Comment by danjohnso** [comment]
Updated my LibProcessable, will check today when servers come back up
