### ISSUE TITLE
Not working in Wrath classic

### ISSUE THREAD

**Issue by jurasekdominik** [p3lim-wow/Molinari#70]
**Describe the bug**
Tried all the options to show the milling button but doesnt work. Tried it with release 84 and 83. 
**How to reproduce**
Holding modifier key over northrend herbs but nothing happens.

**What did you expect?**
To work as intented

**Screenshots**
![image](https://user-images.githubusercontent.com/111370450/193249587-6388fd58-2dd3-45e0-920d-42099cfde7ba.png)

**Comment by p3lim** [comment]
Please try without a bag add-on

**Comment by p3lim** [comment]
Also, you need at least 5 herbs to mill

**Comment by jurasekdominik** [comment]
Tried with all addons disabled, I also tried with enough herbs. On rogue addon is working, maybe there is some requirement for higher inscripton skill ?

**Comment by p3lim** [comment]
Manually milling works?

**Comment by jurasekdominik** [comment]
Yes, it does.

**Comment by promaori** [comment]
@p3lim I had a tinker and found the LibProcessable dependency was missing its .toc for Wrath - I've copied the master from p3lim-wow/LibProcessable and replaced the contents of libs/LibProcessable and now it works.

**Comment by p3lim** [comment]
I forgot to tag LibProcessable, that's the reason it doesn't work :facepalm:

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/LibProcessable/commit/3a2535b1c31dd71e4060418beeffe9368c8b6d80
