### ISSUE TITLE
Disenchant of "special" Enchanter Items in Dragonflight does not work

### ISSUE THREAD

**Issue by fubaWoW** [p3lim-wow/Molinari#80]
Disenchant of "special" Enchanter Items in Dragonflight does not work, means Molinari does not appear on it.  
  
Example Items are:
[Chromatic Pocketwatch](https://www.wowhead.com/item=200939)
[Seal of Order](https://www.wowhead.com/item=200941)
[Carving of Awakening](https://www.wowhead.com/item=200947)
[Valiant Hammer](https://www.wowhead.com/item=200945)
and many more it seems!

**Comment by p3lim** [comment]
I guess this is all of them: https://www.wowhead.com/items/miscellaneous/other?filter=104;0;amount+of+magical+power+can+be+sensed+from+within

**Comment by fubaWoW** [comment]
maybe
i've also figured out that the new "Enchant Rods" also do not work, like this:
[Runed Draconium Rod](https://www.wowhead.com/item=198715)

but they also can be Disenchated

**Comment by p3lim** [comment]
I think that goes for all profession equipment then, and I'll just need to add support for that, no problem.

**Comment by fubaWoW** [comment]
> I think that goes for all profession equipment then, and I'll just need to add support for that, no problem.

yeah i think so, but it's hard to find all of them at wowhead because there is no such filter ^^

**Comment by p3lim** [comment]
I'm not filtering them individually, so that won't be a problem.

**Comment by fubaWoW** [comment]
ok then... just to say -> thanks :D
