### ISSUE TITLE
Molinari.lua:290: attempt to call method 'IsScrappable' (a nil value)

### ISSUE THREAD

**Issue by Ookami313** [p3lim-wow/Molinari#84]
**Describe the bug**
Version 100005.96. Trying to prospect DF ore on my Jewelcrafter causes an error.

**How to reproduce**
ALT+Left clicking ore stack to manually prospect.

**What did you expect?**
No error to occur.

**Screenshots**
41x Molinari/Molinari.lua:290: attempt to call method 'IsScrappable' (a nil value)
[string "@Molinari/Molinari.lua"]:290: in function <Molinari/Molinari.lua:239>
[string "@Molinari/Molinari.lua"]:306: in function <Molinari/Molinari.lua:298>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:278: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:233: in function <SharedXML/Tooltip/TooltipDataHandler.lua:232>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetInventoryItem'
[string "@FrameXML/BankFrame.lua"]:62: in function <FrameXML/BankFrame.lua:59>

Locals:
itemLink = "|cff1eff00|Hitem:1206::::::::70:577:::::::::|h[Moss Agate]|h|r"
itemID = 1206
isMillable = nil
millingSpellID = nil
useMortar = nil
isProspectable = nil
prospectingSpellID = nil
isOpenable = nil
spellID = nil
isOpenableProfession = nil
keyItemID = nil
(*temporary) = nil
(*temporary) = <table> {
 IsProspectable = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:105
 GetProfessionSkillLines = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:396
 IsOpenableProfession = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:299
 IsMillable = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:65
 HasProfession = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:369
 IsOpenable = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:269
 GetProfessionCategories = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:382
 IsDisenchantable = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:142
}
(*temporary) = 1206
(*temporary) = "attempt to call method 'IsScrappable' (a nil value)"
shouldActivate = <function> defined @Molinari/Molinari.lua:215
addon = <table> {
 CreateButtonPool = <function> defined @Molinari/config/ButtonPoolMixin.lua:123
 db = <table> {
 }
 L = <table> {
 }
 eventMixin = <table> {
 }
 CreateBlocklistOptions = <function> defined @Molinari/config/OptionsBlocklist.lua:155
}
LibProcessable = <table> {
 IsProspectable = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:105
 GetProfessionSkillLines = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:396
 IsOpenableProfession = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:299
 IsMillable = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:65
 HasProfession = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:369
 IsOpenable = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:269
 GetProfessionCategories = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:382
 IsDisenchantable = <function> defined @Molinari/libs/LibProcessable/LibProcessable.lua:142
}
Molinari = Molinari {
 CalculateAction = <function> defined @FrameXML/SecureTemplates.lua:609
 ApplyTradeSkill = <function> defined @Molinari/Molinari.lua:70
 0 = <userdata>
 ApplySpell = <function> defined @Molinari/Molinari.lua:22
 RegisterEvent = <function> defined @Molinari/mixins/event.lua:7
 IsEventRegistered = <function> defined @Molinari/mixins/event.lua:39
 GetModifier = <function> defined @Molinari/Molinari.lua:136
 UpdateStateDriver = <function> defined @Molinari/Molinari.lua:201
 SetGlowColor = <function> defined @Molinari/Molinari.lua:128
 Attach = <function> defined @Molinari/Molinari.lua:123
 GetBagAndSlotID = <function> defined @Molinari/Molinari.lua:93
 ApplyItem = <function> defined @Molinari/Molinari.lua:47
 GetGlowColor = <function> defined @Molinari/Molinari.lua:132
 sparkles = <table> {
 }
 UnregisterEvent = <function> defined @Molinari/mixins/event.lua:22
 GetModifierCondition = <function> defined @Molinari/Molinari.lua:148
}
CLASSIC = false

**Comment by Ookami313** [comment]
Looks like you don't have to Left Click on an item in a bag slot. Just holding down ALT and mousing over an item seems to cause the issue.

**Comment by griddark** [comment]
Getting the error even with version 100005.97 tried deleting the mod/savedvariable and reinstalling.

6x Molinari/Molinari.lua:290: attempt to call method 'IsScrappable' (a nil value)
[string "@Molinari/Molinari.lua"]:290: in function <Molinari/Molinari.lua:239>
[string "@Molinari/Molinari.lua"]:306: in function <Molinari/Molinari.lua:298>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:80: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `SetAttribute'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:141: in function <SharedXML/Tooltip/TooltipDataHandler.lua:134>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:278: in function <SharedXML/Tooltip/TooltipDataHandler.lua:236>
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:233: in function <SharedXML/Tooltip/TooltipDataHandler.lua:232>
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `SetBagItem'
[string "@FrameXML/ContainerFrame.lua"]:1497: in function `UpdateTooltip'
[string "@FrameXML/GameTooltip.lua"]:498: in function <FrameXML/GameTooltip.lua:491>

Locals:
itemLink = "|cffa335ee|Hitem:194483::::::::70:581::::1:28:2287:::::|h[Plans: Obsidian Seared Slicer]|h|r"
itemID = 194483
isMillable = nil
millingSpellID = nil
useMortar = nil
isProspectable = nil
prospectingSpellID = nil
isOpenable = nil
spellID = nil
isOpenableProfession = nil
keyItemID = nil
(*temporary) = nil
(*temporary) = <table> {
 IsProspectable = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:105
 GetProfessionSkillLines = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:396
 IsOpenableProfession = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:299
 IsMillable = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:65
 HasProfession = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:369
 IsOpenable = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:269
 GetProfessionCategories = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:382
 IsDisenchantable = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:142
}
(*temporary) = 194483
(*temporary) = "attempt to call method 'IsScrappable' (a nil value)"
shouldActivate = <function> defined @Molinari/Molinari.lua:215
addon = <table> {
 CreateButtonPool = <function> defined @Molinari/config/ButtonPoolMixin.lua:123
 db = <table> {
 }
 L = <table> {
 }
 eventMixin = <table> {
 }
 CreateBlocklistOptions = <function> defined @Molinari/config/OptionsBlocklist.lua:155
}
LibProcessable = <table> {
 IsProspectable = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:105
 GetProfessionSkillLines = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:396
 IsOpenableProfession = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:299
 IsMillable = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:65
 HasProfession = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:369
 IsOpenable = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:269
 GetProfessionCategories = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:382
 IsDisenchantable = <function> defined @ElvUI_SLE/libs/LibProcessable/LibProcessable.lua:142
}
Molinari = Molinari {
 CalculateAction = <function> defined @FrameXML/SecureTemplates.lua:609
 ApplyTradeSkill = <function> defined @Molinari/Molinari.lua:70
 0 = <userdata>
 ApplySpell = <function> defined @Molinari/Molinari.lua:22
 RegisterEvent = <function> defined @Molinari/mixins/event.lua:7
 IsEventRegistered = <function> defined @Molinari/mixins/event.lua:39
 GetModifier = <function> defined @Molinari/Molinari.lua:136
 UpdateStateDriver = <function> defined @Molinari/Molinari.lua:201
 SetGlowColor = <function> defined @Molinari/Molinari.lua:128
 Attach = <function> defined @Molinari/Molinari.lua:123
 GetBagAndSlotID = <function> defined @Molinari/Molinari.lua:93
 ApplyItem = <function> defined @Molinari/Molinari.lua:47
 GetGlowColor = <function> defined @Molinari/Molinari.lua:132
 sparkles = <table> {
 }
 UnregisterEvent = <function> defined @Molinari/mixins/event.lua:22
 GetModifierCondition = <function> defined @Molinari/Molinari.lua:148
}
CLASSIC = false

**Comment by p3lim** [comment]
You have an old version of LibProcessable somewhere.

**Comment by griddark** [comment]
That's was correct.
