### ISSUE TITLE
Lockpicking no longer working in Classic Era version. 

### ISSUE THREAD

**Issue by HolteUnderscore** [p3lim-wow/Molinari#94]
**Describe the bug**

Following the last 2 updates, lockpicking is no longer working in the Classic Era version.
Not tried it in the other versions of WoW.  I'm using the standard "Alt" keybind.

**How to reproduce**

Anytime I try to unlock a locked box.

**What did you expect?**

I expected the box to be engagable with Molinari but, it isn't any longer.

**Screenshots**

**Comment by lierox90** [comment]
same thing for discenchanting, problem is in salvages not existing in classic era in file World of Warcraft\_classic_era_\Interface\AddOns\Molinari\api\items.lua:IsSalvagable() + there is problem with items quality, addon uses new format while game uses old as seen here
![image](https://user-images.githubusercontent.com/4543689/236230916-5cb533b8-0514-4786-ac69-a6fd675bf519.png)

**Comment by p3lim** [comment]
Thanks for spending some time looking at this, it's invaluable since I don't run classic.

I'll take a look when time allows it, please use the <100100 versions in the mean time.

**Comment by Kewlie** [comment]
there is also an issue in wrath classic, line:56 item.lua throws and error

figured a simple fix change Enum.Enum.ItemQuality.Uncommon to Enum.ItemQuality.Good save file /reload UI and works
i believe this would also fix the lockpicking part as well

**Comment by p3lim** [comment]
Please give this alpha version a try:
https://github.com/p3lim-wow/Molinari/suites/12705164241/artifacts/681952062

**Comment by lierox90** [comment]
![image](https://user-images.githubusercontent.com/4543689/236519908-55712561-35d8-458c-8e5b-d84846500ba4.png)
cant prospect on classic era :P

**Comment by p3lim** [comment]
Try this: https://github.com/p3lim-wow/Molinari/suites/12706338085/artifacts/682044609

**Comment by lierox90** [comment]
no error on attempt, dont have green to spare for Dis, will report back asap

**Comment by Kewlie** [comment]
thanks for the fast update ;) this works for disenchanting in wrath

**Comment by lierox90** [comment]
same, works for Dis in classic era

**Comment by ysk5724** [comment]
found 1 more bug in classic era
 
![WoWScrnShot_050623_182738](https://user-images.githubusercontent.com/13391780/236615899-42035f0d-d69d-4b60-93cc-804253d405ae.jpg)

whenever change the modifier option, error occurs.

i tried to change _G.Molinari:UpdateStateDriver() to _G.Molinari:UpdateAttributeDriver() and now it's fine.
