### ISSUE TITLE
Have to click more than once to disenchant

### ISSUE THREAD

**Issue by Neipas09** [p3lim-wow/Molinari#96]
Before patch 10.1, i was able to hold ALT and click on an item, and it would disenchant it.
Now, if i hold ALT and click on an item, it turns the icon Blue and i have to let go of ALT and click on the item again to make it disenchant.

**Comment by Neipas09** [comment]
1. , It's the same no matter what modifiers i use.
2. Disabled all addons except Molinari, and the same thing is happening.

**Comment by BeeJayJayn** [comment]
+1

This is only happening with 10.1 items for me.

**Comment by p3lim** [comment]
I'll need a screenshot or something of this.

**Comment by Neipas09** [comment]
What is a screenshot going to do?

**Comment by p3lim** [comment]
You said the item turned blue, there's nothing in Molinari that would do that.

**Comment by p3lim** [comment]
Ah, thanks for the thorough explanation. I am however unable to reproduce this myself.

**Comment by p3lim** [comment]
What do you get from this? `/dump C_CVar.GetCVarBool('ActionButtonUseKeyDown')`

**Comment by p3lim** [comment]
Also, what bag addon is that?

**Comment by Neipas09** [comment]
The bag addon is AdiBags.
But it happens even when i have all my addons disabled (minus Molinari of course).

**Comment by speedwaystar** [comment]
i also have this issue. thanks for the workaround tip, btw.

**Comment by p3lim** [comment]
Does it work for you in version [100005.97-Release](https://github.com/p3lim-wow/Molinari/releases/tag/100005.97-Release)?

**Comment by Neipas09** [comment]
> /dump C_CVar.GetCVarBool('ActionButtonUseKeyDown')

![2023-05-11 08_29_18-World of Warcraft](https://github.com/p3lim-wow/Molinari/assets/58871039/7092edff-6fa7-4e3b-aabf-b863d5a13222)

**Comment by Neipas09** [comment]
> Does it work for you in version [100005.97-Release](https://github.com/p3lim-wow/Molinari/releases/tag/100005.97-Release)?

Yes, this release version works as expected.

**Comment by Araldwenn** [comment]
Same issue here, but using Arkinventory.

**Comment by p3lim** [comment]
Please use this version and try to disenchant an item as you normally would with Molinari, once. It will output some stuff to the chat, please provide me with a screenshot of this.

https://github.com/p3lim-wow/Molinari/suites/12874499573/artifacts/694483322

**Comment by Neipas09** [comment]
The mouse 'hand icon' turned blue, but did NOT disenchant the item on the first click.

![image](https://github.com/p3lim-wow/Molinari/assets/58871039/76e535a1-fe43-4e8c-a687-b81b676361c1)

**Comment by p3lim** [comment]
Thanks, that helps.

**Comment by p3lim** [comment]
Give this build a shot: https://github.com/p3lim-wow/Molinari/suites/12876941449/artifacts/694635856

Lockpicking is probably broken, need to test that, but disenchanting should work for you now.

**Comment by Neipas09** [comment]
> Give this build a shot: https://github.com/p3lim-wow/Molinari/suites/12877062784/artifacts/694643808
> 
> Lockpicking is probably broken, I need to test that, but disenchanting should work for you now.

Can confirm, disenchanting is working as expected now.

**Comment by p3lim** [comment]
Great, I'll have to verify with classic and wrath, and probably fix lockpicking, then I'll have a new release out.

**Comment by Neipas09** [comment]
Here's a screenshot from trying to do lockpicking on my rogue.

![image](https://github.com/p3lim-wow/Molinari/assets/58871039/526417c4-29b6-48ee-974b-6167ad287110)

And this is using the latest build you posted up above.

**Comment by p3lim** [comment]
Sorry, I should have clarified - lockpicking in trade is probably broken, not lockpicking from bags :)

**Comment by Neipas09** [comment]
Ah ok, i just tested again and it works when the lockbox is in my bag and not in the bank.
![image](https://github.com/p3lim-wow/Molinari/assets/58871039/97245f5b-688b-4625-a71c-e0b4195fefe5)

**Comment by p3lim** [comment]
Thanks for testing, new release is being pushed out now.
