### ISSUE TITLE
Translation:

### ISSUE THREAD

**Issue by dadec666** [p3lim-wow/Molinari#97]
### Which locale are these translations for?

ruRU (Russian)

### "Item Blocklist"

Блок-список предметов

### "Block Item"

Заблокированный предмет

### "Items in this list will not be processed."

Предметы из этого списка не будут обрабатываться.

### "Block a new item by ID"

Заблокировать новый предмет по ID

**Comment by p3lim** [comment]
https://github.com/p3lim-wow/Molinari/commit/ab3e41a67acf6fcd115950117f4673561e9f18d9
