### ISSUE TITLE
Disenchanted wrong item!

### ISSUE THREAD

**Issue by Esperi74** [p3lim-wow/Molinari#99]
I attempted to disenchant a world quest reward I didn't need.  Used the molinari click shortcut (I use Shift-Alt-Left Click for this) and                                                                              instead of DEing the quest reward, it disenchanted my offspec main hand weapon from heroic Vault!  The original world quest drop was still there so I thought it just hadn't worked, did it again and now I have no offhand (got them back via item restore).

I used the regular in-game method to DE it (click disenchant, click item) and it worked as expected.

**Comment by p3lim** [comment]
Molinari uses item GUIDs (unique by every factor) to determine bag slot for the item you are disenchanting, this should not be possible.

**Comment by p3lim** [comment]
Oh, actually, I think I know what's happening.
